# -*- coding: utf-8 -*-
"""3_Exercícios___(1) (1).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10tQO1PoUwxbondNfcYRdrBomsvjJ8Tg_

# Exercícios - Testando Conhecimentos Aprendidos em Aula

### Neste conjunto de exercícios, você será desafiado a aplicar os conceitos aprendidos sobre listas em Python. Os exercícios abrangem operações como criação de listas, remoção de elementos, adição de itens, índices, uso de list comprehensions e muito mais. Siga as instruções de cada exercício e tente resolver utilizando apenas o código dentro do script.

##

### 1 - Crie uma lista contendo os nomes de 5 países. Peça ao usuário para inserir o nome de mais um país. Em seguida, verifique se o país fornecido pelo usuário está na lista e exiba uma mensagem informando se ele está ou não na lista.
"""

paises = ['Afeganistão','Angola','Bosnia','Paraguai','Brasil']

u = input('Insira o nome de um país: ')
usuario = u.capitalize()

if usuario in paises:
    print('Esse país já foi adicionado, insira outro nome')
else:
    print('Nome adicionado')
    paises.append(usuario)
print(paises)

"""### 2 - Crie uma lista contendo os preços de 5 produtos. Em seguida, calcule e exiba o preço médio desses produtos."""

produtos = [25,32,14,21,55]
Media = sum(produtos) / len(produtos)
print ('O preço medio dos produtos sera R${}'.format(Media))

"""  ### 3 - Crie uma lista com 5 cores diferentes. Peça ao usuário para inserir o nome de uma cor. Se a cor estiver na lista, remova-a e exiba a lista atualizada. Caso contrário, exiba uma mensagem informando que a cor não foi encontrada."""

cores = ['roxo','verde','preto','azul','rosa']

usuario = input('Insira o nome de uma cor: ').lower()

if usuario in cores:
    cores.remove(usuario)
    print('Essa cor já excluida')
else:
    cores.append(usuario)
    print('Nome adicionado')
print (cores)

"""### 4 - Escreva um programa que leia duas listas de números do usuário e verifique se elas têm o mesmo comprimento e se possuem elementos iguais nas mesmas posições. Exiba uma mensagem informando se as listas são iguais ou diferentes."""

lista1 = [4,8,40,20,50]
lista2 = [2,4,40,10,25]

if len(lista1) == len(lista2):
    print ('As duas tem o mesmo comprimento')
for i in range(len(lista1)):
        if lista1[i] == lista2[i]:
            print(f"Posição {i}: elementos iguais ({lista1[i]})")
        else:
            print(f"Posição {i}: elementos diferentes ({lista1[i]} != {lista2[i]})")
else:
        print("As listas têm comprimentos diferentes e não podem ser comparadas posição a posição.")

"""### 5 - Crie uma lista contendo 10 números. Em seguida, solicite ao usuário que insira um número. Verifique se o número fornecido pelo usuário está na lista e, se estiver, exiba em quantas posições ele aparece."""

# Lista de números
numeros = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]


numero_usuario = int(input("Digite um número: "))


ocorrencias = numeros.count(numero_usuario)


if ocorrencias > 0:
    print(f"O número {numero_usuario} está na lista e aparece {ocorrencias} vezes.")
else:
    print(f"O número {numero_usuario} não está na lista.")

"""### 6 - Escreva uma função que recebe uma palavra e verifica se é um palíndromo, ou seja, se a palavra é igual quando lida de trás para frente."""

palavra1 = "radar"
palavra2 = "python"

eh_palindromo1 = palavra1 == palavra1[::-1]
eh_palindromo2 = palavra2 == palavra2[::-1]

print(f"{palavra1} é palíndromo?", eh_palindromo1)
print(f"{palavra2} é palíndromo?", eh_palindromo2)

"""### 7 - Escreva uma função que recebe duas listas e retorna uma nova lista que é a concatenação das duas."""

lista1 = [1, 2, 3]
lista2 = [4, 5, 6]
lista_concatenada = lista1 + lista2
print("Lista concatenada:", lista_concatenada)

"""### 8 - Escreva uma função que recebe uma lista e dois índices e troca os elementos presentes nos índices fornecidos."""

lista = [10, 20, 30, 40, 50]
indice1, indice2 = 1, 3
lista[indice1], lista[indice2] = lista[indice2], lista[indice1]
print("Lista trocada:", lista)

"""### 9 - Escreva uma função que recebe uma lista e retorna uma nova lista com os elementos invertidos na ordem."""

lista = [1, 2, 3, 4, 5]
lista_invertida = lista[::-1]
print("Lista invertida:", lista_invertida)

"""### 10 - Escreva uma função que recebe uma lista de palavras e retorna uma nova lista contendo apenas as palavras únicas, ou seja, palavras que aparecem apenas uma vez na lista."""

palavras = ["python", "java", "python", "c", "c++", "java", "python"]
palavras_unicas_lista = [palavra for palavra in palavras if palavras.count(palavra) == 1]
print("Palavras únicas:", palavras_unicas_lista)