# -*- coding: utf-8 -*-
"""Atividades de aperfeiçoamento 05 – Programando em Python (1) (1).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1woDgor88vx8qJMkHXuNiJH-8k5ANqVVL

## 1. Você está organizando uma lista de compras para a feira e deseja que ela esteja em ordem alfabética. Utilize o Python para ordenar a lista de frutas. Depois adicione algumas opções extras à sua lista.
"""

lista = ['maçã','melancia','banana','tomate','abacaxi']
lista.sort()
print(lista)
lista.append('alface')
lista.sort()
print(lista)

"""
## 2. Você está trabalhando com uma lista de números, mas há um valor ‘abc’ incorreto do tipo string misturado. Crie um programa para encontrar e remover esse valor da lista, garantindo que ela contenha apenas números.

"""

lista = ['abc',1,2,3,4,5,6,7,8,9,0]
lista.remove('abc')
print(lista)

"""
## 3. Você está analisando uma lista de números, e gostaria de saber quantos elementos ela possui. Além disso, deseja identificar o maior e o menor número presentes na lista. Use o Python para imprimir o comprimento da lista, o maior e o menor número encontrados.

"""

lista = [99,1,2,3,4,5,6,7,8,9,0]
print(len(lista))
print(max(lista))
print(min(lista))

"""
## 4. Você está gerenciando uma lista de reprodução de músicas e deseja adicionar e remover músicas conforme necessário. Utilize o Python para permitir que o usuário escolha entre adicionar uma nova música ao final da lista ou remover uma música existente.
"""

fila = []
print('fila atual:{}'.format(fila))
escolha = input('Deseja adicionar ou remover uma música ?(add ou rmv)')
if escolha == "add":
    add = input('Escreva o nome da música')
    fila.append(add)
    print('fila atual:{}'.format(fila))
elif escolha == 'rmv':
    rmv = input('Escreva o nome da música a ser retirada da fila')
    try:
        fila.remove(rmv)
        print('fila atual:{}'.format(fila))
    except:
        print('música não existente na fila')
else:
    print('escolha não detectada, escreva add ou rmv. fila atual:{}'.format(fila))

"""## 5. Você possui uma lista de ingredientes para uma receita, e gostaria de substituir um ingrediente específico por outro. Crie um programa para encontrar o ingrediente na lista e substituí-lo."""

lista = ['ovo','leite','açucar','sal','farinha']
listarmv = input('qual item você quer tirar da lista')
listaadd = input('qual item você quer adicionar a lista')
lista.remove(listarmv)
lista.append(listaadd)
print(lista)