# -*- coding: utf-8 -*-
"""atividade 1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wN6B8vU7Vp7kKJDCg7_WDJZ0lkMrAmjk

1. Faça um algoritmo que leia a idade de uma pessoa expressa em anos, meses e dias e escreva a idade
dessa pessoa expressa apenas em dias. Considerar ano com 365 dias e mês com 30 dias.
"""

qtd_a = input ('quantos anos você tem?')
multiplicação = int(variavel) * 365
meses = input ('quantos meses do you have?')
multiplicação_meses = int(meses) * 30
dias = input ('quantos dias')
idade = multiplicação + multiplicação_meses + int(dias)
print (idade)

"""2. Crie um algoritmo capaz de calcular área de um triângulo. O programa deve receber os dados
necessários do usuário (medida da base e da altura do triângulo) e calcular qual seria o valor da área
deste triângulo.
"""

Base = int (input ('Insira a Base'))
altura = int (input ('Insira a Altura'))
área = Base * altura / 2
print (área)

"""3. O custo de um carro novo ao consumidor é a soma do custo de fábrica com a porcentagem do
distribuidor e dos impostos (aplicados ao custo de fábrica). Supondo que o percentual do distribuidor
seja de 28% e os impostos de 45%, escrever um algoritmo para ler o custo de fábrica de um carro,
calcular e escrever o custo final ao consumidor.
"""

fabrica = int (input('Custo de Fabrica'))
distribuidor = 0.028 * fabrica
impostos = 0.045 * fabrica
custo = distribuidor + impostos
print (custo)

"""4. Escreva um algoritmo que calcule a quantidade de latas de tinta necessárias e o custo para pintar
tanques cilíndricos de combustível, dados:
• A lata de tinta custa R$ 50,00;
• Cada lata contém 5 litros;
• Cada litro de tinta pinta 3 m2.
"""

quantidade_de_metros = int (input('Metros quadrados para pintar'))
Preço = 50
Quantidade = 5
Pintar = 3
qtn_l = quantidade_de_metros / Pintar
quantidade_de_latas = qtn_l / Quantidade
custo = Preço * qtn_l
if qtn_l <= 5:
    print('Dar {} litros de tinta que vai dar 1 lata de tinta custando 50 reais'.format(qtn_l))
elif qtn_l > 5:
    print( 'Dar {} litros de tinta que vai dar {} lata de tinta custando {} reais'.format(qtn_l,quantidade_de_latas,custo))

"""5. Você foi contratado por uma empresa chamada ChoppDelyv (Uma empresa de entrega de bebidas a
domicílio concorrente do Zé delivery), esta empresa contratou você para desenvolver os cálculos de
preços do aplicativo dela, logo você deve criar um código simples capaz de receber o nome da bebida
a ser comprada, o valor da bebida a ser comprada, quantas unidades do produto serão vendidas e por
último o programa deve demonstrar uma saída mostrando qual o valor daquela venda.
"""

nome_bebida = str (input ('Nome da Bebida'))
quantidade = int(input ('Quantidade de bebida'))
Preço = 10
valor = Preço * quantidade
print ('O custo total da venda sera da bebida {} vai ser {} Reais' .format(nome_bebida,valor))