# -*- coding: utf-8 -*-
"""Exercícios_Tuplas_ (1).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-Aew7JYR5iTWlmECOf2ovDCq1hRLnPEi

# Exercios de Tuplas

## Vamos explorar a utilidade das tuplas e como elas podem ser aplicadas em várias situações. As tuplas são estruturas de dados imutáveis que permitem armazenar múltiplos elementos de diferentes tipos, tornando-as ideais para representar informações relacionadas de maneira organizada.

### Agora, você está prestes a enfrentar um conjunto de desafios práticos que envolvem o uso de tuplas. Cada exercício foi cuidadosamente criado para ajudá-lo a consolidar seus conhecimentos sobre tuplas e aprimorar suas habilidades de resolução de problemas. Através desses exercícios, você explorará cenários do mundo real, como gerenciamento de estoque, processamento de informações, análise de dados e até mesmo a criação de pequenos jogos.

### À medida que você avança pelos exercícios, lembre-se de aplicar conceitos importantes, como criação de tuplas, indexação, slicing, iteração e cálculos simples. Use sua criatividade e habilidades para encontrar soluções eficientes e elegantes para cada problema proposto. À medida que você se familiariza mais com as tuplas, você também estará desenvolvendo um entendimento mais profundo das estruturas de dados em geral, o que será valioso em suas futuras explorações na programação.

# Exercício 1: Contagem de Vogais
### Crie uma função que recebe uma string e retorna uma tupla contendo a contagem de vogais e consoantes na string.
"""

p = str(input('Digite sua palavra'))
tx = p.lower()
txt = tx.replace(' ','')
cont_vog = 0
cont_cons = 0
vogais = 'aeiou'
for letra in txt:
  if letra in vogais:
    cont_vog += 1
  else:
    cont_cons += 1

print(f'{cont_vog} vogais \n{cont_cons} consoantes')

"""# Exercício 2: Controle de Estoque
### Você está gerenciando o estoque de uma loja. Crie um programa que permita adicionar novos produtos (usando tuplas para nome e preço) ao estoque e exibir o valor total do estoque.
"""

estoque = []
while True:
  print('Deseja adicionar um item ao estoque ? S ou N')
  r = input().capitalize()
  if r == 'N':
    break
  elif r == 'S':
    prod = input('Digite o nome do produto q deseja colocar no estoque: ')
    preço = float(input(f'Digite o valor do produto {prod}: '))
    estoque.append((prod,preço))
  else:
    print('comando não identificado')

print(estoque)

"""# Exercício 3: Análise de Texto
### Crie uma função que recebe um texto e retorna uma tupla contendo a quantidade de palavras e a quantidade média de letras por palavra.
"""

info = []
a = input('digite seu texto/frase: ')
palavras = a.split()
n_palavras = len(palavras)

txt = a.replace(' ','')
p = len(txt)
média = p / n_palavras
info.append((n_palavras,média))
print(f'A quantidade de palavras e a quantidade média de letras por palavra é, respectivamente: {info}')

"""# Exercício 4: Divisão de Despesas
### Você e seus amigos foram a um restaurante e agora precisam dividir a conta. Crie um programa que recebe o valor total da conta e o número de pessoas. Em seguida, calcule quanto cada pessoa deve pagar, considerando um serviço de 10% e usando uma tupla para armazenar os valores.
"""

valor_total_conta = int(input('valor da total da conta R$'))
numero_pessoas = int(input('quantas pessoas vai dividir'))


taxa_servico = valor_total_conta * 0.1
valor_total_com_taxa = valor_total_conta + taxa_servico

# Calcular valor por pessoa
valor_por_pessoa = valor_total_conta / numero_pessoas

#resultado_divisao = (valor_total_com_taxa, valor_por_pessoa)
print(f'O Total da compra foi R$ - {valor_total_conta}, fica para cada um pagar R${valor_por_pessoa:.3f}')

"""# Exercício 5: Contagem de Ocorrências
### Crie uma função que recebe uma lista de elementos e retorna uma tupla contendo a quantidade de ocorrências de um valor específico e a quantidade total de elementos na lista.
"""

numeros = [2, 4, 6, 8, 4, 10, 4]
valor_busca = 4

# Contar ocorrências do valor buscado e calcular total de elementos
quantidade_ocorrencias = numeros.count(valor_busca)
total_elementos = len(numeros)

resultado_contagem = (quantidade_ocorrencias, total_elementos)
print(resultado_contagem)

"""# Exercício 6: Ranking de Notas
### Você está organizando um torneio de videogame. Crie um programa que recebe o nome e a pontuação de cada jogador e os armazena em uma lista de tuplas. Em seguida, exiba o ranking dos jogadores com base em suas pontuações.
"""

jogadores = [('Alice', 150), ('Matheus', 230), ('Eduardo', 180)]

# Ordenar jogadores pelo segundo elemento da tupla (pontuação)
jogadores_ordenados = sorted(jogadores, key=lambda jogador: jogador[1], reverse=True)

# Exibir ranking dos jogadores
for posicao, (nome, pontuacao) in enumerate(jogadores_ordenados, start=1):
    print(f"{posicao}. {nome}: {pontuacao} pontos")

"""# Exercício 7: Processamento de Dados Meteorológicos
### Você possui uma lista de tuplas contendo a temperatura máxima e mínima de cada dia. Crie uma função que calcule a temperatura média de toda a semana e quantos dias a temperatura máxima excedeu 30 graus.
"""

temperaturas_semana = [(28, 32), (30, 31), (25, 28), (32, 35), (27, 30), (31, 34), (29, 33)]

# Calcular temperatura média e dias acima de 30°C
temperatura_media = sum(temperatura[0] for temperatura in temperaturas_semana) / len(temperaturas_semana)
dias_acima_30 = sum(1 for temperatura in temperaturas_semana if temperatura[1] > 30)

resultado_analise = (temperatura_media, dias_acima_30)
print(resultado_analise)

"""# Exercício 8: Divisão Justa
### Você e seus amigos decidiram alugar uma casa de férias. Crie um programa que recebe o valor total do aluguel, as despesas comuns e o número de pessoas. Distribua os custos de forma justa, arredondando para cima, e retorne uma tupla com os valores que cada pessoa deve pagar.
"""

valor_aluguel = 1000
despesas_comuns = [50, 30, 20]
numero_pessoas = 4

# Calcular valor total e valor por pessoa
valor_total = valor_aluguel + sum(despesas_comuns)
valor_por_pessoa = valor_total / numero_pessoas
valor_por_pessoa_arredondado = round(valor_por_pessoa, 2)

resultado_divisao = (valor_total, valor_por_pessoa_arredondado)
print(resultado_divisao)

"""# Exercício 9: Extração de Informações de Texto
### Dado um texto com várias informações em formato "chave: valor", crie uma função que extrai essas informações e as armazena em uma tupla de dicionários.
"""

texto = "Nome: Alice\nIdade: 25\nProfissão: Engenheira\n"
linhas = texto.split('\n')

# Extração das informações e armazenamento em uma lista de dicionários
informacoes = []
for linha in linhas:
    if ':' in linha:
        chave, valor = linha.split(':')
        informacoes.append({chave.strip(): valor.strip()})

# Converter a lista de dicionários em uma tupla
informacoes_extraidas = tuple(informacoes)

print(informacoes_extraidas)

"""# Exercício 10: Jogo de Cartas
### Crie um jogo de cartas em que dois jogadores jogam alternadamente. Cada jogador recebe uma mão de cartas (uma tupla de strings). Implemente a lógica de jogo, como verificar vitória, derrota ou empate, e exiba o resultado após cada rodada.

### Esses exercícios de nível médio a difícil envolvem conceitos mais avançados de manipulação de tuplas e resolução de problemas. Eles podem ajudar a aprofundar sua compreensão das tuplas e como elas podem ser aplicadas em situações mais complexas.
"""

import random
baralho = ['A', '2', '3', '4', '5', '6', '7', '8', '9', '10', 'J', 'Q', 'K']

# Embaralhar o baralho manualmente
n = len(baralho)
for i in range(n - 1, 0, -1):
    j = random.randint(0, i)
    baralho[i], baralho[j] = baralho[j], baralho[i]

# Distribuindo as cartas para os jogadores
mao_jogador1 = tuple(baralho[:3])
mao_jogador2 = tuple(baralho[3:6])

# Exibindo as mãos dos jogadores
print(f"Jogador 1: {mao_jogador1}")
print(f"Jogador 2: {mao_jogador2}")

# Verificando o vencedor ou empate
if mao_jogador1 > mao_jogador2:
    print("Jogador 1 venceu!")
elif mao_jogador2 > mao_jogador1:
    print("Jogador 2 venceu!")
else:
    print("Empate!")

