# -*- coding: utf-8 -*-
"""Exercícios_Explorando_mais_Bibliotecas_.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18YYxhjFpuEyyWGShJDL4XISaIRJJ5pxc

# Explorando -  A Arte de Dominar Bibliotecas Essenciais"

### Na era digital atual, a habilidade de manipular e controlar a tecnologia é um diferencial estratégico que pode determinar o sucesso em muitas áreas de atuação. Python, sendo uma das linguagens de programação mais populares e versáteis, oferece uma vasta gama de bibliotecas que permitem aos desenvolvedores realizar desde tarefas simples até complexas operações de engenharia de software e análise de dados.

### Bibliotecas bem desenvolvidas e mantidas podem reduzir drasticamente o tempo de desenvolvimento de software, cada biblioteca Python foi criada para resolver um tipo específico de problema. Ao compreender o propósito e a aplicação de diferentes bibliotecas, os programadores podem escolher a melhor ferramenta para a tarefa em questão, permitindo uma resolução de problemas mais eficaz e criativa.
"""



"""# 1. Pygame - Criando uma janela básica

## Você deseja criar um jogo simples e precisa começar com o básico. Crie uma janela usando Pygame que possa ser usada como a tela principal do seu jogo.

### Bibliotecas/Métodos: pygame.init(), pygame.display.set_mode(), pygame.display.set_caption(), pygame.quit()
"""

# Crie seu codigo aqui !
# Importa a biblioteca pygame para podermos usá-la
import pygame

# Inicializa todos os módulos do pygame (som, vídeo, teclado, etc.)
pygame.init()

# Define o tamanho da janela do jogo (largura=800px, altura=600px)
tela = pygame.display.set_mode((800, 600))

# Define o título da janela (o texto que aparece na barra superior)
pygame.display.set_caption("Minha primeira janela com Pygame")

# Variável de controle para manter o jogo rodando
rodando = True

# Loop principal do jogo (enquanto 'rodando' for True, a janela fica aberta)
while rodando:
    # Captura os eventos (como clique, teclas, fechar a janela, etc.)
    for evento in pygame.event.get():
        # Se o evento for "QUIT" (clicar no X da janela), o jogo para
        if evento.type == pygame.QUIT:
            rodando = False

# Encerra o pygame e fecha a janela corretamente
pygame.quit()

"""# 2. SoundFile - Gravando e lendo um arquivo de áudio

##  Você está desenvolvendo uma aplicação para ajudar no aprendizado de línguas e precisa implementar uma funcionalidade que permita aos usuários gravar suas pronúncias e ouvi-las posteriormente.

### Bibliotecas/Métodos: soundfile, sounddevice, numpy
"""

# Crie seu codigo aqui !

# Importa a biblioteca sounddevice, usada para gravar e reproduzir áudio
import sounddevice as sd

# Importa a biblioteca soundfile, usada para salvar e ler arquivos de áudio
import soundfile as sf

# Importa o numpy, que será usado para lidar com arrays de dados do áudio
import numpy as np

# Define o nome do arquivo de áudio que será salvo
arquivo = "gravacao.wav"

# Define a duração da gravação em segundos (aqui: 5 segundos)
duracao = 5

# Define a taxa de amostragem (quantidade de amostras por segundo, 44100 é padrão de qualidade de CD)
taxa_amostragem = 44100

# Informa ao usuário que a gravação vai começar
print("Gravando... fale agora!")

# Grava o áudio do microfone por 'duracao' segundos
gravacao = sd.rec(int(duracao * taxa_amostragem), samplerate=taxa_amostragem, channels=2, dtype='float32')

# Espera a gravação terminar antes de prosseguir
sd.wait()

# Informa que a gravação terminou
print("Gravação finalizada!")

# Salva o áudio gravado no arquivo .wav
sf.write(arquivo, gravacao, taxa_amostragem)

# Informa ao usuário que o áudio foi salvo
print(f"Áudio salvo como {arquivo}")

# Agora, lê o arquivo salvo para reproduzir
dados, samplerate = sf.read(arquivo)

# Informa que a reprodução vai começar
print("Reproduzindo o áudio...")

# Reproduz o áudio gravado
sd.play(dados, samplerate)

# Espera a reprodução terminar
sd.wait()

"""# 3. Colorama - Colorindo texto no terminal

## Você está criando um script para console que exibe logs de diferentes severidades. Implemente um sistema para mostrar mensagens de erro em vermelho, avisos em amarelo e mensagens de informação em azul.

### Bibliotecas/Métodos: colorama.Fore, colorama.Style
"""

# Crie seu codigo aqui !

# Importa a biblioteca colorama, usada para colorir textos no terminal
from colorama import Fore, Style, init

# Inicializa o colorama (necessário no Windows para funcionar corretamente)
init(autoreset=True)

# Exibe uma mensagem de informação em azul
print(Fore.BLUE + "INFO: O sistema foi iniciado com sucesso.")

# Exibe uma mensagem de aviso em amarelo
print(Fore.YELLOW + "AVISO: A conexão com a internet está instável.")

# Exibe uma mensagem de erro em vermelho
print(Fore.RED + "ERRO: Não foi possível acessar o banco de dados!")

# Exibe uma mensagem normal (sem cor), usando Style.RESET_ALL
print(Style.RESET_ALL + "Mensagem padrão sem destaque.")

"""# 4. OpenCV (cv2) - Exibindo uma imagem

## Você está trabalhando em um software de visualização de imagens médicas e precisa implementar uma funcionalidade que permita aos usuários abrir e visualizar imagens de exames.

### Bibliotecas/Métodos: cv2.imread(), cv2.imshow(), cv2.waitKey(), cv2.destroyAllWindows()
"""

# Crie seu codigo aqui !

# Importa a biblioteca OpenCV (cv2) para processamento e exibição de imagens
import cv2

# Define o caminho do arquivo da imagem que será exibida
# Substitua "exame.png" pelo nome do arquivo real
imagem = cv2.imread("exame.png")

# Verifica se a imagem foi carregada corretamente
if imagem is None:
    print("Erro: Não foi possível carregar a imagem.")
else:
    # Exibe a imagem em uma janela chamada "Exame Médico"
    cv2.imshow("Exame Médico", imagem)

    # Espera o usuário pressionar qualquer tecla para fechar a janela
    cv2.waitKey(0)

    # Fecha todas as janelas abertas do OpenCV
    cv2.destroyAllWindows()

"""# 5. Pygame - Capturando eventos do teclado

## Desenvolva um minijogo onde o usuário deve pressionar a tecla espaço para fazer um personagem pular. Implemente a detecção dessa tecla para iniciar o salto.

## Bibliotecas/Métodos: pygame.KEYDOWN, pygame.K_SPACE
"""

# Crie seu codigo aqui !
# Importa a biblioteca pygame
import pygame

# Inicializa o pygame
pygame.init()

# Define o tamanho da tela
largura, altura = 800, 400
tela = pygame.display.set_mode((largura, altura))

# Define o título da janela
pygame.display.set_caption("Mini Jogo - Pular com Espaço")

# Define a cor branca para o fundo
BRANCO = (255, 255, 255)

# Define a cor azul para o personagem
AZUL = (0, 0, 255)

# Define a posição inicial do personagem
x = 100
y = 300

# Define o tamanho do personagem
largura_personagem = 50
altura_personagem = 50

# Variáveis de controle do pulo
pulando = False
forca_pulo = 15   # intensidade do pulo
gravidade = 1     # força que puxa o personagem para baixo
velocidade_y = 0  # velocidade vertical

# Controle do loop principal
rodando = True
clock = pygame.time.Clock()

# Loop principal do jogo
while rodando:
    # Define FPS (frames por segundo)
    clock.tick(60)

    # Preenche o fundo com branco
    tela.fill(BRANCO)

    # Desenha o personagem (um retângulo azul)
    pygame.draw.rect(tela, AZUL, (x, y, largura_personagem, altura_personagem))

    # Atualiza a tela
    pygame.display.update()

    # Captura eventos
    for evento in pygame.event.get():
        # Fecha a janela se o usuário clicar no "X"
        if evento.type == pygame.QUIT:
            rodando = False

        # Detecta se uma tecla foi pressionada
        if evento.type == pygame.KEYDOWN:
            # Se a tecla for espaço e o personagem não estiver no ar, inicia o pulo
            if evento.key == pygame.K_SPACE and not pulando:
                pulando = True
                velocidade_y = -forca_pulo  # movimento para cima

    # Lógica do pulo
    if pulando:
        y += velocidade_y   # aplica a velocidade na posição
        velocidade_y += gravidade  # aplica a gravidade

        # Se o personagem tocar o chão, para o pulo
        if y >= 300:
            y = 300
            pulando = False

# Encerra o pygame
pygame.quit()

"""# 6. Colorama - Alternando cores e estilos

##  Seu script de terminal gera um relatório de status de diferentes servidores. Use cores e estilos diferentes para indicar o status de cada servidor (ativo, inativo, em manutenção).

### Bibliotecas/Métodos: colorama.Fore, colorama.Back, colorama.Style
"""

# Crie seu codigo aqui !

"""# 7. OpenCV (cv2) - Convertendo imagens para escala de cinza

## Você está trabalhando em um software de edição de fotos que precisa de uma ferramenta para converter fotos coloridas para preto e branco. Implemente esta funcionalidade usando OpenCV.

### Bibliotecas/Métodos: cv2.cvtColor(), cv2.COLOR_BGR2GRAY
"""

# Crie seu codigo aqui !

"""# 8. Pygame - Desenhando formas geométricas

##  Você está desenvolvendo um aplicativo educativo para ensinar geometria básica para crianças. Implemente uma interface onde formas geométricas como retângulos, círculos e triângulos são desenhados e identificados com etiquetas.

### Bibliotecas/Métodos: pygame.draw.rect(), pygame.draw.circle(), pygame.draw.polygon()
"""

# Crie seu codigo aqui !

"""#                                               -------------Desafio _____________

# 9.  Flet - Criando um formulário de feedback

## Objetivo: Desenvolver um formulário simples para coletar feedback dos usuários utilizando a biblioteca Flet. O formulário deve conter campos para nome, e-mail, e um espaço para o usuário escrever suas impressões ou sugestões.

# Bibliotecas/Métodos:

## flet (importar Page, TextField, Text, Button, Column)

## Você está ajudando a organizar um evento de tecnologia e precisa criar uma aplicação para coletar feedback dos participantes. O formulário deve ser acessível e fácil de usar, coletando informações básicas e impressões dos participantes.
"""

# Crie seu codigo aqui !

