# -*- coding: utf-8 -*-
"""Exercícios_Estrutura_While_ (1).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1EmpYXu1Fi4L5CeMqxE558XbEztU5KISk

# Desafios de Treinamento em Python com o Loop While



#### "Desafios de Treinamento em Python com o Loop While"! Você está prestes a embarcar em uma jornada emocionante para aprimorar suas habilidades de programação usando a linguagem Python. Os exercícios que apresentamos aqui foram projetados para proporcionar a você uma compreensão sólida e prática do loop while, uma ferramenta poderosa que permite que seu código execute repetidamente enquanto uma condição for verdadeira.

#### À medida que você trabalha nesses exercícios, você estará mergulhando em situações do mundo real, resolvendo problemas e construindo soluções criativas usando o loop while. Essa é uma oportunidade incrível para fortalecer sua lógica de programação e sua capacidade de transformar conceitos abstratos em código funcional.

##### Cada exercício apresenta uma situação desafiadora que requer o uso eficaz do loop while. Ao enfrentar esses desafios, você não apenas dominará os aspectos técnicos da linguagem Python, mas também desenvolverá uma abordagem analítica para resolver problemas complexos de maneira iterativa e estruturada.

#### Lembre-se de que a prática é fundamental para aprimorar suas habilidades. Reserve um tempo para entender completamente cada exercício, experimentar diferentes abordagens e testar suas soluções. Se encontrar dificuldades, não hesite em pesquisar documentações, tutoriais e recursos online para obter insights adicionais.
"""

venda = [250, 330, 440, 540, 350, 250, 368, 40, 250, 30, 30]
vendedores = ['maria', 'mara', 'joão', 'silva', 'santos', 'mario', 'carlos', 'marly', 'xuxa', 'chica', 'zinha']
meta = 500

i = 0

while i < len(venda):
    if venda[i] >= meta:
        print('{} atingiu a meta de vendas: {}'.format(vendedores[i], venda[i]))
    i += 1

"""## Exercício 1: Contagem regressiva
Situação Problema: Você está lançando um foguete espacial e deseja fazer uma contagem regressiva a partir de 10 até o lançamento. Escreva um programa que imprima os números de 30 a 1, indicando a contagem regressiva.


"""

i = 30

while i > 0:
    i = i - 1
    print('Contagem regressiva: {}'.format(i))

"""### Exercício 2: Soma até certo limite
Situação Problema: Você está jogando um jogo em que precisa somar números inteiros sequencialmente até que a soma ultrapasse 20. Escreva um programa que calcule e exiba a soma desses números.


"""

numeros = []

while sum(numeros) <= 20:
    numero = int(input('Digite um numero: '))
    numeros.append(numero)

print('A soma dos numeros é: {}'.format(sum(numeros)))

"""### Exercício 3: Adivinhe o número
Situação Problema: Você está brincando de adivinhar o número que um computador escolheu entre 1 e 100. Cada vez que você adivinha, o computador lhe dirá se o número é maior ou menor. Escreva um programa que permita que o jogador adivinhe o número e conte quantas tentativas foram necessárias.


"""

numero_secreto = 57  # Substitua por qualquer número desejado
tentativas = 0

print('Bem-vindo ao jogo de adivinhação!')
print('Tente adivinhar o número.')

while True:
    palpite = int(input('Digite seu palpite: '))
    tentativas += 1

    if palpite == numero_secreto:
        print(f'Parabéns! Você acertou o número {numero_secreto} em {tentativas} tentativa(s).')
        break
    elif palpite < numero_secreto:
        print('O número é maior. Tente novamente.')
    else:
        print('O número é menor. Tente novamente.')

"""### Exercício 4: Tabuada
Situação Problema: Você é um estudante tentando aprender a tabuada. Escreva um programa que peça um número ao usuário e, em seguida, exiba a tabuada desse número, de 1 a 10.


"""

numero = int(input("Digite um numero: "))

i = 0

while i < 10:
    i = i + 1
    print("A TABUADA DO NUMERO {} É: {}".format(numero, (numero * i)))
    if i == 10:
      break

"""### Exercício 5: Soma de números pares
Situação Problema: Você está tentando calcular a soma de todos os números pares de 2 a 100. Escreva um programa que realize essa tarefa.


"""

numeros = []

i = 0

while i < 100:
    i = i + 2
    numeros.append(i)

soma = sum(numeros)
print(numeros)
print('A soma dos numeros pares de 1 a 100 é igual a: {}'.format(soma))

# Calculadora de calorias queimadas sem funções e dicionários.

# Tabela de cone (equivalentes metabólicos) hardcoded.
caminhada_met = 3.0
corrida_met = 6.0
natação_met = 6.0
ciclismo_met = 4.0
musculação_met = 3.0

# Solicitar informações ao usuário.
tipo_exercicio = input("Digite o tipo de exercício realizado (caminhada, corrida, natação, ciclismo, musculação): ")
duracao = int(input("Digite a duração do exercício em minutos: "))
peso = float(input("Digite o seu peso em kg: "))

# Definir o MET baseado no tipo de exercício.
if tipo_exercicio.lower() == "caminhada":
  met = caminhada_met
elif tipo_exercicio.lower() == "corrida":
  met = corrida_met
elif tipo_exercicio.lower() == "natação":
  met = natação_met
elif tipo_exercicio.lower() == "ciclismo":
  met = ciclismo_met
elif tipo_exercicio.lower() == "musculação":
  met = musculação_met
else:
  print("Tipo de exercício inválido.")
  exit()

# Calcular o gasto calórico por minuto.
gasto_calorico_minuto = met * peso * 0.0175

# Calcular o gasto calórico total.
gasto_calorico_total = gasto_calorico_minuto * duracao

# Exibir a quantidade de calorias queimadas.
print(f"Você queimou aproximadamente {gasto_calorico_total:.2f} calorias durante o exercício.")

"""### Exercício 6: Média de números
Situação Problema: Você é um professor que deseja calcular a média das notas de seus alunos. Escreva um programa que permita que o professor insira as notas dos alunos e calcule a média.


"""

total_notas = 0
quantidade_alunos = 0

print('Calculadora de Média de Notas')

while True:
        nota = float(input('Digite a nota do aluno (ou digite -1 para encerrar): '))
        if 0 <= nota <= 10:
            total_notas += nota
            quantidade_alunos += 1
        elif nota == -1:
            break  # Encerra o loop se -1 for digitado
        else:
            print('Por favor, digite uma nota válida entre 0 e 10.')

if quantidade_alunos > 0:
    media = total_notas / quantidade_alunos
    print(f'A média das notas dos {quantidade_alunos} alunos é: {media:.2f}')
else:
    print('Nenhuma nota válida foi inserida.')

"""### Exercício 7: Fatorial
Situação Problema: Você está resolvendo problemas matemáticos e precisa calcular o fatorial de um número inteiro. Escreva um programa que calcule e exiba o fatorial de um número dado.


"""

numero = int(input('Digite um número para calcular o fatorial: '))

if numero < 0:
    print('O fatorial não está definido para números negativos.')
elif numero == 0:
    print('O fatorial de 0 é 1.')
else:
    fatorial = 1
    contador = 1

    while contador <= numero:
        fatorial *= contador
        contador += 1

    print(f'O fatorial de {numero} é: {fatorial}')

"""### Exercício 8: Números primos
Situação Problema: Você está explorando números primos e deseja verificar se um determinado número é primo. Escreva um programa que permita que o usuário insira um número e determine se ele é primo ou não.


"""

numero_inserido = int(input('Digite um número para verificar se é primo: '))

# Verifica se o número é primo
if numero_inserido < 2:
    print('{} não é um número primo.'.format(numero_inserido))
elif numero_inserido == 2:
    print(f'{numero_inserido} é um número primo.')
elif numero_inserido % 2 == 0:
    print(f'{numero_inserido} não é um número primo.')
else:
    divisor = 3

    while divisor * divisor <= numero_inserido:
        if numero_inserido % divisor == 0:
            print(f'{numero_inserido} não é um número primo.')
            break
        divisor += 2  # Pula para o próximo número ímpar
    else:
        print(f'{numero_inserido} é um número primo.')

"""### Exercício 9: Soma até ultrapassar valor
Situação Problema: Você está tentando descobrir quantos números inteiros precisam ser somados sequencialmente até que a soma total seja maior que 100. Escreva um programa que realize esse cálculo.

"""

soma = 0
contador = 0

while soma <= 100:
    contador += 1
    soma += contador
    print(soma)

print(f'Foram necessários {contador} números para a soma ultrapassar 100.')

"""
### Exercício 10: Validando entrada numérica
Situação Problema: Você está criando um programa que requer entrada numérica do usuário. No entanto, você deseja garantir que a entrada seja válida. Escreva um programa que solicite ao usuário um número e continue pedindo até que um número válido seja inserido.

"""

while True:
    try:
        numero = float(input('Digite um número: '))
        if numero == 103:
          break  # Sai do loop se a entrada for válida
        else:
            print('Por favor, tente novamente')
    except ValueError:
        print('Por favor, digite um número válido.')

print(f'Você digitou o número: {numero}')



"""### Exercício 12: Contagem de vogais
Situação Problema: Você está analisando palavras e deseja saber quantas vogais cada palavra contém. Escreva um programa que conte e exiba o número de vogais em uma palavra inserida pelo usuário.


"""

palavra = input('Digite uma palavra: ').lower()  # Converte para minúsculas para considerar maiúsculas e minúsculas
vogais = 'aeiou'
contagem_vogais = 0
indice = 0

while indice < len(palavra):
    if palavra[indice] in vogais:
        contagem_vogais += 1
    indice += 1

print(f'A palavra "{palavra}" contém {contagem_vogais} vogais.')

"""### Exercício 13: Média de notas com validação
Situação Problema: Você é um professor que deseja calcular a média das notas de seus alunos. No entanto, você também deseja validar as notas para garantir que estejam dentro de um intervalo adequado. Escreva um programa que permita que o professor insira as notas dos alunos, valide-as e calcule a média.
"""

quantidade_alunos = int(input('Digite a quantidade de alunos: '))

soma_notas = 0
notas_validas = 0

for aluno in range(1, quantidade_alunos + 1):
    while True:
        try:
            nota = float(input(f'Digite a nota do aluno {aluno}: '))
            if 0 <= nota <= 10:
                soma_notas += nota
                notas_validas += 1
                break  # Sai do loop se a nota for válida
            else:
                print('Por favor, digite uma nota válida entre 0 e 10.')
        except ValueError:
            print('Por favor, digite um número válido.')

if notas_validas > 0:
    media = soma_notas / notas_validas
    print(f'A média das notas dos {quantidade_alunos} alunos é: {media:.2f}')
else:
    print('Nenhuma nota válida foi inserida.')