# -*- coding: utf-8 -*-
"""Explorando_Bibliotecas_Python (1).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kVj2BOUjfv2M5OjigLv6DRpJfWl5lkfR

# Explorando -  A Arte de Dominar Bibliotecas Essenciais"

### Na era digital atual, a habilidade de manipular e controlar a tecnologia é um diferencial estratégico que pode determinar o sucesso em muitas áreas de atuação. Python, sendo uma das linguagens de programação mais populares e versáteis, oferece uma vasta gama de bibliotecas que permitem aos desenvolvedores realizar desde tarefas simples até complexas operações de engenharia de software e análise de dados.

### Bibliotecas bem desenvolvidas e mantidas podem reduzir drasticamente o tempo de desenvolvimento de software, cada biblioteca Python foi criada para resolver um tipo específico de problema. Ao compreender o propósito e a aplicação de diferentes bibliotecas, os programadores podem escolher a melhor ferramenta para a tarefa em questão, permitindo uma resolução de problemas mais eficaz e criativa.
"""



"""# 1. Pygame - Criando uma janela básica

## Você deseja criar um jogo simples e precisa começar com o básico. Crie uma janela usando Pygame que possa ser usada como a tela principal do seu jogo.

### Bibliotecas/Métodos: pygame.init(), pygame.display.set_mode(), pygame.display.set_caption(), pygame.quit()
"""

python3 game.py

import pygame

# Inicializa o Pygame
pygame.init()

# Define as dimensões da janela
largura = 800
altura = 600
tela = pygame.display.set_mode((largura, altura))

# Define o título da janela
pygame.display.set_caption("Movimento do Quadrado")

# Cores
BRANCO = (255, 255, 255)
VERDE = (0, 255, 0)

# Posições iniciais do quadrado
x, y = 350, 250
velocidade = 5

# Loop principal do jogo
executando = True
while executando:
    for evento in pygame.event.get():
        if evento.type == pygame.QUIT:
            executando = False

    # Captura as teclas pressionadas
    teclas = pygame.key.get_pressed()

    if teclas[pygame.K_LEFT]:
        x -= velocidade
    if teclas[pygame.K_RIGHT]:
        x += velocidade
    if teclas[pygame.K_UP]:
        y -= velocidade
    if teclas[pygame.K_DOWN]:
        y += velocidade

    # Preenche a tela com a cor branca
    tela.fill(BRANCO)

    # Desenha o quadrado na nova posição
    pygame.draw.rect(tela, VERDE, (x, y, 50, 50))

    # Atualiza a tela
    pygame.display.update()

    # Controla o FPS (frames por segundo)
    pygame.time.Clock().tick(60)

# Finaliza o Pygame
pygame.quit()

"""# 2. SoundFile - Gravando e lendo um arquivo de áudio

##  Você está desenvolvendo uma aplicação para ajudar no aprendizado de línguas e precisa implementar uma funcionalidade que permita aos usuários gravar suas pronúncias e ouvi-las posteriormente.

### Bibliotecas/Métodos: soundfile, sounddevice, numpy
"""

pip install soundfile sounddevice numpy

# Crie seu codigo aqui !
import sounddevice as sd
import soundfile as sf
import numpy as np

# Função para gravar o áudio
def gravar_audio(duracao, taxa_amostragem=44100, nome_arquivo="gravacao.wav"):
    print("Gravando...")

    # Grava o áudio usando o microfone
    grava = sd.rec(int(duracao * taxa_amostragem), samplerate=taxa_amostragem, channels=1, dtype='float32')
    sd.wait()  # Espera até a gravação terminar

    # Salva o áudio em um arquivo WAV
    sf.write(nome_arquivo, grava, taxa_amostragem)
    print(f"Áudio gravado e salvo como {nome_arquivo}")

# Função para reproduzir o áudio gravado
def reproduzir_audio(nome_arquivo="gravacao.wav"):
    # Lê o arquivo de áudio gravado
    dados, taxa_amostragem = sf.read(nome_arquivo)

    # Reproduz o áudio
    print(f"Reproduzindo {nome_arquivo}...")
    sd.play(dados, taxa_amostragem)
    sd.wait()  # Espera até o áudio terminar de tocar

# Configurações
duracao = 5  # duração da gravação em segundos
nome_arquivo = "gravacao.wav"

# Grava o áudio
gravar_audio(duracao, nome_arquivo=nome_arquivo)

# Reproduz o áudio gravado
reproduzir_audio(nome_arquivo=nome_arquivo)

"""# 3. Colorama - Colorindo texto no terminal

## Você está criando um script para console que exibe logs de diferentes severidades. Implemente um sistema para mostrar mensagens de erro em vermelho, avisos em amarelo e mensagens de informação em azul.

### Bibliotecas/Métodos: colorama.Fore, colorama.Style
"""

pip install colorama

from IPython.display import display, HTML

# Função para exibir logs coloridos em Jupyter
def log_erro(mensagem):
    display(HTML(f'<p style="color:red; font-weight:bold;">[ERRO] {mensagem}</p>'))

def log_aviso(mensagem):
    display(HTML(f'<p style="color:yellow; font-weight:bold;">[AVISO] {mensagem}</p>'))

def log_info(mensagem):
    display(HTML(f'<p style="color:blue; font-weight:bold;">[INFO] {mensagem}</p>'))

# Exemplo de uso
log_erro("Falha ao conectar ao banco de dados.")
log_aviso("Atenção: O uso de memória está alto.")
log_info("Sistema iniciado com sucesso.")

"""# 4. OpenCV (cv2) - Exibindo uma imagem

## Você está trabalhando em um software de visualização de imagens médicas e precisa implementar uma funcionalidade que permita aos usuários abrir e visualizar imagens de exames.

### Bibliotecas/Métodos: cv2.imread(), cv2.imshow(), cv2.waitKey(), cv2.destroyAllWindows()
"""

pip install opencv-python

# Crie seu codigo aqui !
import cv2

# Caminho da imagem (substitua pelo caminho do seu arquivo)
caminho_imagem = 'shape 2.png'

# Carrega a imagem
imagem = cv2.imread(caminho_imagem)

# Verifica se a imagem foi carregada corretamente
if imagem is None:
    print("Erro ao carregar a imagem.")
else:
    # Exibe a imagem em uma janela
    cv2.imshow("Exibição da Imagem", imagem)

    # Espera até que qualquer tecla seja pressionada
    cv2.waitKey(0)

    # Fecha todas as janelas abertas
    cv2.destroyAllWindows()

"""# 5. Pygame - Capturando eventos do teclado

## Desenvolva um minijogo onde o usuário deve pressionar a tecla espaço para fazer um personagem pular. Implemente a detecção dessa tecla para iniciar o salto.

## Bibliotecas/Métodos: pygame.KEYDOWN, pygame.K_SPACE
"""

import pygame

# Inicializa o Pygame
pygame.init()

# Configurações da janela
largura = 800
altura = 600
tela = pygame.display.set_mode((largura, altura))
pygame.display.set_caption("Minijogo: Pulo do Personagem")

# Cores
BRANCO = (255, 255, 255)
AZUL = (0, 0, 255)

# Variáveis do personagem
largura_personagem = 50
altura_personagem = 50
x = largura // 2 - largura_personagem // 2
y = altura - altura_personagem
velocidade = 5
pulo = False
altura_pulo = 0
forca_gravidade = 1

# Controle de tempo
clock = pygame.time.Clock()

# Loop principal do jogo
executando = True
while executando:
    for evento in pygame.event.get():
        if evento.type == pygame.QUIT:
            executando = False
        # Detectando se a tecla espaço foi pressionada
        if evento.type == pygame.KEYDOWN:
            if evento.key == pygame.K_SPACE and not pulo:
                pulo = True
                altura_pulo = 20  # Altura inicial do pulo

    # Atualizar a posição do personagem
    if pulo:
        # Fazendo o personagem pular
        y -= altura_pulo
        altura_pulo -= forca_gravidade  # Diminui a altura do pulo
        if altura_pulo <= 0:  # Quando atingir o pico do pulo, começa a cair
            pulo = False

    if not pulo and y < altura - altura_personagem:  # Personagem cai até o chão
        y += forca_gravidade

    # Preenche a tela com cor branca
    tela.fill(BRANCO)

    # Desenha o personagem
    pygame.draw.rect(tela, AZUL, (x, y, largura_personagem, altura_personagem))

    # Atualiza a tela
    pygame.display.update()

    # Controla o FPS (frames por segundo)
    clock.tick(60)

# Finaliza o Pygame
pygame.quit()

"""# 6. Colorama - Alternando cores e estilos

##  Seu script de terminal gera um relatório de status de diferentes servidores. Use cores e estilos diferentes para indicar o status de cada servidor (ativo, inativo, em manutenção).

### Bibliotecas/Métodos: colorama.Fore, colorama.Back, colorama.Style
"""

from IPython.display import display, HTML

# Função para gerar o relatório de status dos servidores no Jupyter
def status_servidor_html(nome, status):
    if status == 'ativo':
        estilo = 'font-weight: bold; color: green; background-color: black; padding: 5px;'
    elif status == 'inativo':
        estilo = 'font-weight: bold; color: red; background-color: black; padding: 5px;'
    elif status == 'manutencao':
        estilo = 'font-weight: bold; color: yellow; background-color: black; padding: 5px;'
    else:
        estilo = 'font-weight: bold; color: white; background-color: black; padding: 5px;'

    # Gerar a string HTML para o servidor
    return f'<p style="{estilo}">Servidor {nome}: {status.upper()}</p>'

# Lista de servidores e seus status
servidores = [
    ("Servidor 1", "ativo"),
    ("Servidor 2", "inativo"),
    ("Servidor 3", "manutencao"),
    ("Servidor 4", "ativo")
]

# Gerar e exibir o relatório completo
relatorio = ""
for nome, status in servidores:
    relatorio += status_servidor_html(nome, status)

# Exibir o relatório no Jupyter
display(HTML(relatorio))

"""# 7. OpenCV (cv2) - Convertendo imagens para escala de cinza

## Você está trabalhando em um software de edição de fotos que precisa de uma ferramenta para converter fotos coloridas para preto e branco. Implemente esta funcionalidade usando OpenCV.

### Bibliotecas/Métodos: cv2.cvtColor(), cv2.COLOR_BGR2GRAY
"""

pip install opencv-python

# Crie seu codigo aqui !
import cv2
import matplotlib.pyplot as plt

# Carrega a imagem colorida
# Altere 'caminho_da_imagem.jpg' para o caminho da imagem desejada no seu sistema
imagem = cv2.imread('shape 2.png')

# Converte a imagem de BGR (padrão OpenCV) para escala de cinza
imagem_cinza = cv2.cvtColor(imagem, cv2.COLOR_BGR2GRAY)

# Exibe a imagem original e a convertida para escala de cinza
plt.figure(figsize=(10,5))

# Subplot 1: Imagem original
plt.subplot(1, 2, 1)
plt.imshow(cv2.cvtColor(imagem, cv2.COLOR_BGR2RGB))  # Convertendo de BGR para RGB para exibir corretamente no matplotlib
plt.title("Imagem Original")
plt.axis('off')  # Remove os eixos

# Subplot 2: Imagem em escala de cinza
plt.subplot(1, 2, 2)
plt.imshow(imagem_cinza, cmap='gray')
plt.title("Escala de Cinza")
plt.axis('off')  # Remove os eixos

# Mostra as imagens
plt.show()

"""# 8. Pygame - Desenhando formas geométricas

##  Você está desenvolvendo um aplicativo educativo para ensinar geometria básica para crianças. Implemente uma interface onde formas geométricas como retângulos, círculos e triângulos são desenhados e identificados com etiquetas.

### Bibliotecas/Métodos: pygame.draw.rect(), pygame.draw.circle(), pygame.draw.polygon()
"""

import pygame
import sys

# Inicializando o Pygame
pygame.init()

# Definindo as dimensões da janela
largura, altura = 600, 400
tela = pygame.display.set_mode((largura, altura))
pygame.display.set_caption("Formas Geométricas")

# Definindo cores
BRANCO = (255, 255, 255)
VERDE = (0, 255, 0)
AZUL = (0, 0, 255)
VERMELHO = (255, 0, 0)

# Fonte para as etiquetas
fonte = pygame.font.Font(None, 36)

# Função para desenhar e identificar formas geométricas
def desenhar_formas():
    # Preenche a tela com cor branca
    tela.fill(BRANCO)

    # Desenhando um retângulo
    pygame.draw.rect(tela, VERDE, (50, 50, 150, 100))
    texto_retangulo = fonte.render("Retângulo", True, VERDE)
    tela.blit(texto_retangulo, (50, 50))

    # Desenhando um círculo
    pygame.draw.circle(tela, AZUL, (300, 150), 50)
    texto_circulo = fonte.render("Círculo", True, AZUL)
    tela.blit(texto_circulo, (250, 150))

    # Desenhando um triângulo
    pontos = [(500, 100), (450, 200), (550, 200)]
    pygame.draw.polygon(tela, VERMELHO, pontos)
    texto_triangulo = fonte.render("Triângulo", True, VERMELHO)
    tela.blit(texto_triangulo, (460, 210))

    # Atualiza a tela
    pygame.display.flip()

# Função principal do jogo
def main():
    # Loop principal do jogo
    while True:
        # Captura eventos (como fechar a janela)
        for evento in pygame.event.get():
            if evento.type == pygame.QUIT:
                pygame.quit()
                sys.exit()

        # Chama a função para desenhar as formas
        desenhar_formas()

        # Definir a taxa de atualização
        pygame.time.Clock().tick(60)

# Executa o jogo
main()

"""#                                               -------------Desafio _____________

# 9.  Flet - Criando um formulário de feedback

## Objetivo: Desenvolver um formulário simples para coletar feedback dos usuários utilizando a biblioteca Flet. O formulário deve conter campos para nome, e-mail, e um espaço para o usuário escrever suas impressões ou sugestões.

# Bibliotecas/Métodos:

## flet (importar Page, TextField, Text, Button, Column)

## Você está ajudando a organizar um evento de tecnologia e precisa criar uma aplicação para coletar feedback dos participantes. O formulário deve ser acessível e fácil de usar, coletando informações básicas e impressões dos participantes.
"""

# Crie seu codigo aqui !

pip install flet

import ipywidgets as widgets
from IPython.display import display

# Função para processar o feedback
def on_button_click(b):
    nome = nome_text.value
    email = email_text.value
    feedback = feedback_text.value

    # Exibe o feedback enviado
    print(f"Obrigado pelo seu feedback, {nome}!")
    print(f"Você pode ser contatado pelo e-mail: {email}")
    print(f"Sua sugestão: {feedback}")

# Criando os widgets (campos de texto)
nome_text = widgets.Text(description="Nome:")
email_text = widgets.Text(description="E-mail:")
feedback_text = widgets.Textarea(description="Feedback:", layout=widgets.Layout(width='500px', height='200px'))

# Criando o botão de envio
button = widgets.Button(description="Enviar")

# Definindo o que acontece quando o botão é pressionado
button.on_click(on_button_click)

# Exibindo os widgets no Jupyter
display(nome_text, email_text, feedback_text, button)

