# -*- coding: utf-8 -*-
"""ifelse3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1U5T2uXxLFujevZ7VSGFxUpCUFWGAiHFs

3.1
"""

num1 = float(input('digite o primeiro valor'))
num2 = float(input('digite o segundo valor'))
operacao = int(input('escolha a operação que você quer fazer com esses números \n1-Adição \n2-Subtração \n3-Multiplicação \n4-Divisão'))
if operacao == 1:
    print(num1 + num2)
elif operacao == 2:
    print(num1 - num2)
elif operacao == 3:
    print(num1 * num2)
elif operacao == 4:
    print(num1 / num2)
else:
    print('opção inválida, repita o código e escolha uma opção válida')

"""3.2"""

altura = float(input('Digite sua altura'))
peso = float(input('Digite seu peso'))
imc = peso / (altura * altura)
if imc < 18.5:
    print('Abaixo do peso, {}'.format(imc))
elif imc >= 18.5 and imc < 24.9:
    print('Peso normal, {}'.format(imc))
elif imc >= 25 and imc < 29.9:
    print('Sobrepeso, {}'.format(imc))
elif imc >= 30 and imc < 34.9:
    print('Obesidade, Grau I, {}'.format(imc))
elif imc >= 35 and imc < 39.9:
    print('Obesidade, Grau II, {}'.format(imc))
elif imc > 40:
    print('Obesidade, Grau III, {}'.format(imc))

"""3.3"""

temp = float(input('Digite a temperatura desejada'))
conv = int(input('Digite a conversão desejada \n1-C para F \n2-F para C'))
if conv == 1:
    print((temp * 1.8) + 32)
elif conv == 2:
    print((temp - 32) * 5/9)
else:
    print('opção inválida')

"""3.4"""

user = str(input('Digite seu usuário'))
senha = input('Digite sua senha')
if user == 'admin' and senha == 'senha123':
    print('Acesso Concedido')
else:
    print('Acesso Negado')

"""3.5"""

lado1 = float(input('Digite a medida do primeiro lado'))
lado2 = float(input('Digite a medida do segundo lado'))
lado3 = float(input('Digite a medida do terceiro lado'))
conta = lado1 + lado2 > lado3 and lado1 + lado3 > lado2 and lado2 + lado3 > lado1
if conta is True and lado1 == lado2 and lado1 == lado3 and lado2 == lado3:
    print('Equilátero')
elif conta is True and lado1 == lado2 and lado1 != lado3 or lado1 == lado3 and lado1 != lado2 or lado3 == lado2 and lado3 != lado1:
    print('Isóceles')
elif conta is True and lado1 != lado2 and lado1 != lado3 and lado2 != lado3:
    print('Escaleno')
else:
    print('não é possível formar um triângulo')