# -*- coding: utf-8 -*-
"""ifelse2&3 (2).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GjhNCzk7JTNczRZsv-FjdCxKG3L-pwhl

# 2.1
"""

valor = float(input('Digite o seu valor'))
if valor >= 0:
    print('Positivo')
else:
    print('Negativo')

"""2.2"""

letra = input('digite uma letra')
if letra in ('a', 'e', 'i', 'o', 'u','A', 'E', 'I', 'O', 'U'):
    print('Vogal')
else:
    print('Consoante')

"""2.3"""

num = int(input('Digite um número'))
if num == 1:
    print('Domingo')
elif num == 2:
    print('Segunda')
elif num == 3:
    print('Terça')
elif num == 4:
    print('Quarta')
elif num == 5:
    print('Quinta')
elif num == 6:
    print('Sexta')
elif num == 7:
    print('Sábado')
else:
    print('Valor Inválido, selecione um valor de 1 a 7')

"""2.4"""

media = float(input('Selecione sua média'))
if media >= 6:
    print('Aprovado')
else:
    print('Reprovado')

"""# 3.1

"""

tarefas = int(input('Digite a quantidade de tarefas'))
if tarefas % 2 == 0:
    print('Tarefas distribuídas de forma igual, par')
else:
    print('Tira a última tarefa no Jo Ken Po, ímpar')

"""3.2"""

idade = int(input('Digite sua idade'))
if idade >= 18:
    print('Maior de idade, siga sem restrições')
else:
    print('Menor de idade,necessário acompanhante')

"""3.3"""

num1 = float(input("Escreva o primeiro valor"))
num2 = float(input("Escreva o segundo valor"))
if num1 > num2:
    print("o valor {} é maior q o valor {}".format(num1,num2))
elif num2 > num1:
    print("o valor {} é maior q o valor {}".format(num2,num1))
elif num1 == num2:
    print("valores iguais")
else:
    print("erro no código")

"""3.4"""

preco = float(input('Qual o valor da sua compra?'))
if preco > 100:
    valor = preco - (preco * 0.010)
    print('sua compra teve desconto, indo para o valor de R$' + str(valor))
else:
    print('sem desconto')

"""3.5"""

nota = float(input('digite sua nota'))
if nota >= 9:
    print('A')
elif nota >= 7 and nota < 9:
    print('B')
elif nota >= 5 and nota < 7:
    print('C')
elif nota >=3 and nota < 5:
    print('D')
elif nota >= 1 and nota < 3:
    print('E')
else:
    print('valor inválido')