# -*- coding: utf-8 -*-
"""Importação de bliblioteca.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1q6Q4-Q8YQkFiqP1D7RPdsMKUFJPCb7BE

# **Exercício 1:**

---

Faça um programa que calcule a raiz quadrada de um número inteiro fornecido pelo usuário. Utilize a biblioteca math para realizar o cálculo.
"""

import math
res=int(input('Digite um número que queira descobrir sua raiz'))
print(f'O resultado da raiz de {res} é {math.sqrt(res)}')

"""# **Exercício 2:**

---

Crie um programa que gere um número aleatório entre 1 e 100 e peça ao usuário para adivinhar qual é esse número. Utilize a biblioteca random para gerar o número aleatório.
"""

##### import random as rd
secret = random.randint(1, 100)
chances = rd.randint(5,10)

for repeat in range(chances):
    print(f'Você tem {chances} pra acertar o número sortido')
    question = int(input('Tente adivinhar o número: '))
    print('-----------------------------------------')
    if secret == question:
        print(f'Parabens você acertou o número que era {secret}')
        break
    elif secret > question:
        print('Seu número é menor do que o sorteado')
        print('-----------------------------------------')
        chances -= 1
    else:
        print('Seu número é maior do que o sorteado')
        print('-----------------------------------------')
        chances -= 1
print(f'O número sorteado é {secret}')

"""# **Exercício 3:**

---
Crie um programa que simule um lançamento de dados. O programa deve gerar um número aleatório entre 1 e 6, representando o valor do dado. Utilizar função randint da biblioteca random
"""

question = int(input('Digite a quantidade de vezes que você quer rodar os dados'))
for rodadas in range(question):
    dado = rd.randint(1,6)
    print(dado)

"""# **Exercício 4:**

---
Faça um programa que calcule a área de um círculo. O usuário deve fornecer o raio do círculo como entrada. Utilize a biblioteca math para obter o valor de π (pi).
"""

question = float(input('Digite o raio que deseja calcular a area do circulo'))
area = math.pi * question**2
print(round(area,2))

"""# **Exercício 5:**

---
Crie um programa que solicite ao usuário um nome de arquivo e, em seguida, leia o conteúdo desse arquivo e conte quantas palavras diferentes existem no texto. Utilize Counter da biblioteca collections para ajudar na contagem.

python
C
"""

from collections import Counter
question = str(input('Digite o uma frase e conte quantas palavras diferentes existem no texto '))
text = question.lower().split()
print(Counter(text))

"""# **Exercício 6:**

---
Crie um programa que solicite ao usuário uma lista de números separados por vírgula e exiba a média desses números. Utilize a função mean da biblioteca statistics.
"""

import statistics as stat
while True:
    list = str(input('Escrevas todos os números em sequencia com espaço que você gostaria de fazer a media: '))
    print('-------------------------------------------------------------------------------------------------')
    print(list.split())
    res = str(input('É essas notas que vc quer fazer a media? Y or N: '))
    print('-------------------------------------------------------------------------------------------------')
    if res.lower() == 'y':
        lista_number =[float(num) for num in list.split()]
        print(lista_number)
        media_lista = stat.mean(lista_number)
        print(f'Sua media é {media_lista}')
        break
    elif res.lower() == 'n':
        print('Exemplo pratico logo abaixo, escreva os números com esse espaçamento')
        print('10 20 30 40 50')
        print('-------------------------------------------------------------------------------------------------')
        continue

"""# **Exercício 7:**

---
Crie um programa usando a biblioteca tkinter que exiba uma janela com um botão. Quando o botão for clicado, exiba uma mensagem de saudação usando a função messagebox.showinfo().

"""

import tkinter as tk
from tkinter import messagebox
janela = tk.Tk()
label = tk.Label(janela, text="Olá")
botao = tk.Button(janela, text = 'X', messagebox.showinfo('tchau'))

label.pack()
botao.pack()

import tkinter as tk
from tkinter import messagebox

janela = tk.Tk()
janela.title('Tela inicial')
janela.geometry("600x300")
label = tk.Label(janela, text="Bem-vindo ao nosso programa de demonstração!\n"
         "Este é um exemplo de como usar o Tkinter para criar interfaces gráficas.\n"
         "Digite seu nome no campo abaixo e clique em Enviar para receber uma mensagem personalizada.",
        font = ("Arial",12),
        wraplength=480)
botao = tk.Button(janela, text='clique aqui', command=lambda: messagebox.showinfo('Aviso', 'Olha que curioso kkkkk'))

label.pack()
botao.pack()
janela.mainloop()

"""# **Exercício 8:**

---
Crie um programa usando a biblioteca tkinter que exiba uma janela com um rótulo de texto e um campo de entrada. Quando o botão for clicado, obtenha o texto do campo de entrada usando a função .get() e exiba uma mensagem de boas-vindas personalizada usando a função messagebox.showinfo().

"""

def get_registro():
    registro = entrada.get()
    messagebox.showinfo('Registro',registro)

janela = tk.Tk()
janela.title('test_zone')
janela.geometry('600x400')

texto_init = tk.Label(janela, text ='Escreva algo na caixa abaixo, por favor', font = ('Arial',14))
texto_init.pack()

entrada = tk.Entry(janela)
entrada.pack(pady=10)

botao = tk.Button(janela, text = 'confirmar escrita',command=get_registro)
botao.pack(pady=10)

janela.mainloop()


print(registro)

"""# **Exercício 9:**

---
Crie um programa usando a biblioteca tkinter que exiba uma janela com uma caixa de seleção e um botão. Quando o botão for clicado, obtenha a opção selecionada da caixa de seleção usando a variável associada e exiba-a em uma caixa de diálogo usando a função messagebox.showinfo().
"""

import tkinter as tk
from tkinter import messagebox

def mostrar_seleção():
    # Obtém o valor selecionado na caixa de seleção
    selecionado = var.get()
    # Exibe a seleção em uma caixa de diálogo
    messagebox.showinfo("Seleção", f"A opção selecionada foi: {selecionado}")

# Criação da janela principal
window = tk.Tk()
window.title('Exemplo de Caixa de Seleção')
window.geometry('500x600')

# Variável associada à caixa de seleção
var = tk.StringVar()

# Criação da caixa de seleção com opções
opcao1 = tk.Radiobutton(window, text="Opção 1", variable=var, value="Opção 1")
opcao1.pack()

opcao2 = tk.Radiobutton(window, text="Opção 2", variable=var, value="Opção 2")
opcao2.pack()

opcao3 = tk.Radiobutton(window, text="Opção 3", variable=var, value="Opção 3")
opcao3.pack()

# Criação do botão que chama a função ao ser clicado
botao = tk.Button(window, text="Mostrar Seleção", command=mostrar_seleção)
botao.pack()

# Inicia a aplicação
window.mainloop()

"""# **Exercício 10:**

---
Crie um programa que utilize a biblioteca pandas para ler um arquivo CSV chamado "dados.csv". O arquivo contém uma coluna chamada "idade". Calcule a média das idades utilizando o método .mean() e exiba o resultado.

[Link para a Documentação do Pandas](https://pandas.pydata.org/docs/reference/api/pandas.read_csv.html)

"""

import pandas as pd

# Lê o arquivo CSV
df = pd.read_csv('dados.csv')

# Calcula a média da coluna "idade"
media_idade = df['idade'].mean()

# Exibe o resultado
print(f'A média das idades é: {media_idade}')

"""# **Exercício 11:**

---
Crie um programa que utilize as bibliotecas pandas e matplotlib para ler um arquivo CSV chamado "dados.csv". O arquivo contém duas colunas: "nome" e "pontuacao". Exiba um gráfico de barras utilizando o método .bar() do matplotlib.pyplot, passando os nomes como valores no eixo x e as pontuações como valores no eixo y.

[Link para a Documentação do Pandas](https://pandas.pydata.org/docs/reference/api/pandas.read_csv.html)

[Link para a documentação do matplotlib](https://matplotlib.org/stable/api/_as_gen/matplotlib.pyplot.bar.html)
"""

import pandas as pd
import matplotlib.pyplot as plt

# Lê o arquivo CSV
df = pd.read_csv('dados_pontuação.csv')

# Exibe as primeiras linhas do DataFrame para verificar o conteúdo
print(df.head())

# Cria o gráfico de barras
plt.bar(df['nome'], df['pontuacao'])

# Adiciona título e rótulos aos eixos
plt.title('Pontuação dos Participantes')
plt.xlabel('Nome')
plt.ylabel('Pontuação')

# Exibe o gráfico
plt.show()

