# -*- coding: utf-8 -*-
"""Situação 1,2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1FifaxPrZKlQiH4-cRQuvZhNokcIcyMAr
"""

carro = str(input('Qual carro pretende locar?'))
diaria = str(input('Qual o valor da diária do aluguel?'))
km = str(input('Qual o valor por km rodados?'))
kmh = str(input('Quantos km pretende percorrer com o carro?'))
dias = str(input('Quantos dias pretende locar o carro?'))
print('Você locou um {} (Ótima escolha), sendo R$ {} por dia e R$ {} por km, e percorrerá {} km durante {} dias. Obrigado pela sua preferência, qualquer dúvida sobre o veículo contate-nos (11) 912345678.'.format(carro, diaria, km, kmh, dias))



