# -*- coding: utf-8 -*-
"""While_02 (1).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KIpsOVWQHvwb9PgNwV1OI5IZ33LZZEq4

# Cuidado com o while -> Loop Infinito

Sempre que for usar o comando while, lembre-se de ter certeza que o programa vai terminar em algum momento

### Exemplo

Digamos que temos uma lista de vendedores e as quantidades vendidas e queremos identificar todos os vendedores que bateram a meta de 50 vendas.
"""

vendas = [941, 852, 783, 714, 697, 686, 685, 670, 631, 453, 386, 371, 294, 269, 259, 218, 208, 163, 125, 102, 87, 47, 7]
vendedores = ['Maria', 'José', 'Antônio', 'João', 'Francisco', 'Ana', 'Luiz', 'Paulo', 'Carlos', 'Manoel', 'Pedro', 'Francisca', 'Marcos', 'Raimundo', 'Sebastião', 'Antônia', 'Marcelo', 'Jorge', 'Márcia', 'Geraldo', 'Adriana', 'Sandra', 'Luis']
meta = 50

i = 0
while i < len(vendas) and vendas[i] > meta:
    print('{} bateu a meta. Vendas: {}'.format(vendedores[i], vendas[i]))
    i += 1