# -*- coding: utf-8 -*-
"""Cópia de While_01.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1PFm8qW6dsRlsmGryHfOVKXLs5DF6AZEQ

# Estrutura while:

### Funcionamento:

Usamos o while quando queremos repetir um código de forma indeterminada até uma condição se tornar verdadeira/falsa.

A lógica é: enquanto a condição for verdadeira, o while executa o código. Assim que ela terminar de ser verdadeira, o código "sai" do while.

while condicao:
    repete esse código

- Exemplo: Quando criamos automações na internet
- Exemplo2: Crie um programa que funcione como o registro de vendas de uma empresa.

Nele, a pessoa deve inserir o nome do produto e o produto deve ser adicionado na lista de venda. Enquanto o usuário não encerrar o programa, significa que ele está registrando novos produtos, então o programa deve permitir e entrada de quantos produtos o usuário quiser.
"""

venda = input('Registre um produto. Para cancelar o registro de um novo produto, basta apertar enter com a caixa vazia')
vendas = []
#crie aqui o programa
while venda != '':
  vendas.append(venda)
  venda = input('Registre um produto. Para cancelar o registro de um novo produto, basta apertar enter com a caixa vazia')
print('Registro Finalizado. As vendas cadastradas foram: {}'.format(vendas))